version: '3.8'

services:
  server:
    build:
      context: .
    command: python3 -m flask run --host=0.0.0.0
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
